<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.3.36812.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiSorterLib\MultiSorterLib.csproj" />
    <ProjectReference Include="..\TestFileGenerator\TestFileGenerator.csproj" />
  </ItemGroup>

</Project>
