namespace MultiSorterLib
{
    /// <summary>
    /// Provides functionality to sort alphanumeric entities from an input file and save the sorted results to an output
    /// file.
    /// </summary>
    /// <remarks>This class reads entities from a specified input file, sorts them in ascending order, and
    /// writes the sorted entities to an output file with "_Sorted" appended to the original file name. The class
    /// manages resources associated with file operations and should be disposed when no longer needed. Instances are
    /// not thread-safe.</remarks>
    public sealed class AlphanumericSorterHelper : IDisposable
    {
        private readonly string? inputFileName;
        private readonly ulong inputFileSize = 0;
        private readonly bool canBeRunInAvailablePhysicalMemory = false;
        private readonly string? outputFileName;

        private IEnumerable<AlphanumericEntity>? entities;
        private List<string>? sortedChunkFiles;

        public string OutputFileName => outputFileName ?? string.Empty;

        /// <summary>
        /// Initializes a new instance of the AlphanumericSorterHelper class using the specified input file.
        /// </summary>
        /// <remarks>The output file will be created in the same directory as the input file, with
        /// "_Sorted" appended to its name before the file extension.</remarks>
        /// <param name="fileName">The path to the input file containing entities to be sorted. Must refer to an existing file.</param>
        /// <exception cref="FileNotFoundException">Thrown if the file specified by <paramref name="fileName"/> does not exist.</exception>
        public AlphanumericSorterHelper(string fileName)
        {
            if (!File.Exists(fileName))
            {
                throw new FileNotFoundException("The specified input file was not found.", fileName);
            }

            inputFileName = fileName;
            inputFileSize = (ulong)new FileInfo(fileName).Length;
            canBeRunInAvailablePhysicalMemory = 2 * inputFileSize < SystemMemoryHelper.GetAvailablePhysicalMemoryBytes();

            // The following `Path.GetDirectoryName()` possible nullable warning is suppressed
            //  as it's checked to be a valid directory path just a line above
            outputFileName = Path.Combine(
                Path.GetDirectoryName(fileName)!,
                Path.GetFileNameWithoutExtension(fileName) +
                "_Sorted" + Path.GetExtension(fileName));
        }
        
        /// <summary>
        /// Sorts the entities from the input file, using either in-memory or external sorting depending on available
        /// physical memory.
        /// </summary>
        /// <remarks>If sufficient physical memory is available, the method performs an in-memory sort for
        /// improved performance. Otherwise, it uses an external sorting algorithm, which may involve temporary files
        /// and slower processing. The sorting operation prepares the entities for subsequent access in sorted
        /// order.</remarks>
        /// <exception cref="FileNotFoundException">Thrown if the input file name is not specified or is invalid.</exception>
        public void Sort()
        {
            if (string.IsNullOrWhiteSpace(inputFileName))
            {
                throw new FileNotFoundException("Input file name is not specified or is invalid.");
            }

            if (canBeRunInAvailablePhysicalMemory)
            {
                entities = EnumerateEntities(File.ReadLines(inputFileName));
                var sortedEntities = entities.ToArray().Order();

                entities.GetEnumerator().Dispose();
                entities = null;
                entities = sortedEntities;
            }
            else
            {
                // If the data cannot be sorted in memory, need to use an external sorting algorithm here
                sortedChunkFiles = ExternalSorter.CreateSortedChunks(inputFileName);
            }
        }

        /// <summary>
        /// Writes the sorted output data to the specified output file. Uses in-memory or external sorting based on
        /// available memory and data size.
        /// </summary>
        /// <remarks>If the data set is small enough to fit in available physical memory, the output is
        /// written directly from memory. For larger data sets, external sorting is used and the output is generated by
        /// merging sorted chunk files. Ensure that the output file name is valid and accessible before calling this
        /// method.</remarks>
        /// <exception cref="FileNotFoundException">Thrown if the output file name is not specified or is invalid.</exception>
        public void SaveOutputFile()
        {
            if (string.IsNullOrWhiteSpace(outputFileName))
            {
                throw new FileNotFoundException("Output file name is not specified or is invalid.");
            }

            if (canBeRunInAvailablePhysicalMemory && entities != null && entities.LongCount() > 0)
            {
                File.WriteAllLines(outputFileName, entities.Select(s => s.EntityLine));
            }
            else if (sortedChunkFiles != null && sortedChunkFiles.Count > 0)
            {
                // If the data cannot be sorted in memory, need to use an external sorting algorithm here
                // and write the output file (merge) as part of that process
                Merger.MergeSortedFiles(sortedChunkFiles, outputFileName ?? string.Empty);
            }
        }

        /// <summary>
        /// Enumerates alphanumeric entities parsed from a sequence of input lines.
        /// </summary>
        /// <remarks>Lines that do not match the expected format or contain invalid numeric values are
        /// skipped. The method disposes the enumerator for the input sequence when enumeration is complete.</remarks>
        /// <param name="lines">The collection of strings to parse, where each line is expected to contain a numeric value and an
        /// alphanumeric identifier separated by a delimiter.</param>
        /// <returns>An enumerable collection of <see cref="AlphanumericEntity"/> objects parsed from the input lines. Only lines
        /// that can be successfully parsed into an entity are included.</returns>
        public static IEnumerable<AlphanumericEntity> EnumerateEntities(IEnumerable<string> lines)
        {
            IEnumerator<string> enumerator = lines.GetEnumerator();

            try
            {
                string[]? parts;
                while (enumerator.MoveNext())
                {
                    parts = GetSplit(enumerator.Current, AlphanumericEntity.Delimiter).ToArray();

                    if (parts != null && parts.Length == 2 && int.TryParse(parts[0].Trim(), out int numericPart))
                    {
                        yield return new AlphanumericEntity(parts[1].Trim(), numericPart);
                    }
                }
            }
            finally
            {
                enumerator.Dispose();
            }
        }

        /// <summary>
        /// Releases all resources used by the current instance.
        /// </summary>
        /// <remarks>Call this method when the instance is no longer needed to free associated resources.
        /// After calling Dispose, the instance should not be used.</remarks>
        public void Dispose()
        {
            entities?.GetEnumerator().Dispose();
            entities = null;

            sortedChunkFiles?.ForEach(f => File.Delete(f));
            sortedChunkFiles?.Clear();
            sortedChunkFiles = null;
        }

        /// <summary>
        /// Splits the specified string into substrings based on the provided delimiter character.
        /// </summary>
        /// <remarks>Empty substrings are not included in the result. The method does not return empty
        /// entries between consecutive delimiters or at the start/end of the string.</remarks>
        /// <param name="s">The string to be split. If the delimiter is not found, the original string is returned as a single element.</param>
        /// <param name="c">The character used as the delimiter for splitting the string.</param>
        /// <returns>An enumerable collection of substrings resulting from splitting the input string by the specified delimiter.
        /// Substrings are non-empty, and the original string is returned as a single element if the delimiter is not
        /// present.</returns>
        private static IEnumerable<string> GetSplit(string s, char c)
        {
            int l = s.Length;
            int i = 0, j = s.IndexOf(c, 0, l);

            if (j == -1) // No such substring
            {
                yield return s; // Return original and break
                yield break;
            }

            while (j != -1)
            {
                if (j - i > 0) // Non empty? 
                {
                    yield return s.Substring(i, j - i); // Return non-empty match
                }
                i = j + 1;
                j = s.IndexOf(c, i, l - i);
            }

            if (i < l) // Has remainder?
            {
                yield return s.Substring(i, l - i); // Return remaining trail
            }
        }
    }
}
